#include "lua_light.h"
#include "tiles.h"

LUA_DEFINE_CLASS(LightSource)
LUA_CLASS_CONSTRUCTOR(LightSource,
	InitializeLight,INT_ARG(0),INT_ARG(1),INT_ARG(2),INT_ARG(3),INT_ARG(4),BOOL_ARG(5))
LUA_BEGIN_CLASS_METHODS(LightSource)
	LUA_REGISTER_CLASS_METHOD(LightSource,CastLight)
	LUA_REGISTER_CLASS_METHOD(LightSource,CastStaticLight)
	LUA_REGISTER_CLASS_METHOD(LightSource,SetLightColor)
LUA_END_CLASS_METHODS(LightSource)
LUA_BEGIN_CLASS_INT_MEMBERS(LightSource)
	LUA_FIRST_CLASS_MEMBER(x)
	LUA_CLASS_MEMBER(y)
	LUA_CLASS_MEMBER(radius)
	LUA_CLASS_MEMBER(intensity)
LUA_END_CLASS_INT_MEMBERS

LUA_DEFINE_CLASS_METHOD_VOID(LightSource,CastLight);
LUA_DEFINE_CLASS_METHOD_VOID(LightSource,CastStaticLight);
LUA_DEFINE_CLASS_METHOD_VOID(LightSource,SetLightColor,INT_ARG(1));
